name: Build APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Tools
        run: sudo apt-get update && sudo apt-get install -y cmake ninja-build

      - name: Build Debug APK
        run: |
          cd $(find . -name "gradlew" -exec dirname {} \;)
          chmod +x gradlew
          # Compilamos la versión DEBUG para evitar errores de firma
          ./gradlew assembleDebug --no-daemon -Dorg.gradle.jvmargs="-Xmx3g"
