name: Build APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Find and Build
        run: |
          # Este comando busca dónde está el archivo gradlew automáticamente
          GRADLE_PATH=$(find . -name gradlew)
          chmod +x $GRADLE_PATH
          cd $(dirname $GRADLE_PATH)
          ./gradlew assembleRelease --no-daemon
