name: Build APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Build Tools
        run: sudo apt-get install -y cmake ninja-build

      - name: Build with Gradle
        run: |
          # Busca la carpeta de Android y compila limitando la memoria
          cd $(find . -name "gradlew" -exec dirname {} \;)
          chmod +x gradlew
          ./gradlew assembleRelease -Pandroid.skipCc=true --no-daemon -Dorg.gradle.jvmargs="-Xmx4g"
